// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_18.Data;

#nullable disable

namespace project_18.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617093812_UpdateSeededProductsAndCategories")]
    partial class UpdateSeededProductsAndCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("project_18.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electronic Devices"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Home Appliances"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Furniture"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("project_18.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("project_18.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Condition = "Good",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slight scratches on the sides, but the screen is in perfect condition. Battery health is at 86%. Includes original box and charging cable.",
                            ImageUrl = "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=500",
                            IsSold = false,
                            Name = "Used iPhone 13 Pro (128GB) - Graphite",
                            Price = 450.00m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Condition = "Very Good",
                            CreatedAt = new DateTime(2026, 6, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2K resolution (2560x1440) IPS panel. No dead pixels. Great for office work or gaming. Power cable and HDMI included.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500",
                            IsSold = false,
                            Name = "Dell UltraSharp 27\" Monitor (U2719D)",
                            Price = 120.00m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Condition = "Very Good",
                            CreatedAt = new DateTime(2026, 6, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Active noise-canceling headphones in black. Ear cups show minor signs of wear but sound quality is superb. Case and audio jack included.",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
                            IsSold = false,
                            Name = "Sony WH-1000XM4 Wireless Headphones",
                            Price = 140.00m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Condition = "Excellent",
                            CreatedAt = new DateTime(2026, 6, 4, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Only used a few times, extremely clean inside. Perfect for healthy cooking. Temperature dial and timer work flawlessly.",
                            ImageUrl = "https://images.unsplash.com/photo-1621972750749-0fbb1abb7736?w=500",
                            IsSold = false,
                            Name = "Philips Air Fryer XXL",
                            Price = 75.00m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Condition = "Good",
                            CreatedAt = new DateTime(2026, 6, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "One-touch milk system coffee maker. Fully descaled and ready to use. Makes amazing lattes and cappuccinos.",
                            ImageUrl = "https://images.unsplash.com/photo-1579888944880-d98341148733?w=500",
                            IsSold = false,
                            Name = "Nespresso Lattissima Touch Coffee Machine",
                            Price = 110.00m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            Condition = "Very Good",
                            CreatedAt = new DateTime(2026, 6, 6, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Grey 2-seater sofa in modern style. Fabric has no tears or stains. Ideal for small apartments or living rooms.",
                            ImageUrl = "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500",
                            IsSold = false,
                            Name = "Modern Fabric Loveseat Sofa",
                            Price = 220.00m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Condition = "Good",
                            CreatedAt = new DateTime(2026, 6, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sturdy wooden desk with 3 drawers. Perfect for students or home office. Minor surface scuffs on the top.",
                            ImageUrl = "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500",
                            IsSold = false,
                            Name = "Solid Wood Study Desk",
                            Price = 95.00m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Condition = "Very Good",
                            CreatedAt = new DateTime(2026, 6, 8, 17, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Black mesh high-back chair with lumbar support. Height adjustable and tilt tension control work perfectly.",
                            ImageUrl = "https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=500",
                            IsSold = false,
                            Name = "Adjustable Ergonomic Office Chair",
                            Price = 65.00m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            Condition = "Very Good",
                            CreatedAt = new DateTime(2026, 6, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Size 32/32, dark blue wash. Very clean, no rips or discoloration. Classic slim fit denim.",
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500",
                            IsSold = false,
                            Name = "Men's Levi's 511 Slim Fit Jeans",
                            Price = 25.00m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4,
                            Condition = "Good",
                            CreatedAt = new DateTime(2026, 6, 10, 19, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Size M, black windbreaker. Waterproof material still works perfectly. Zipper and hood adjustments are intact.",
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
                            IsSold = false,
                            Name = "North Face Waterproof Windbreaker Jacket",
                            Price = 48.00m
                        });
                });

            modelBuilder.Entity("project_18.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "BalaMarket Admin",
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("project_18.Models.Order", b =>
                {
                    b.HasOne("project_18.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("project_18.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_18.Models.Product", b =>
                {
                    b.HasOne("project_18.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("project_18.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("project_18.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
