// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_18.Data;

#nullable disable

namespace project_18.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614223933_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("project_18.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Vintage Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Collectibles & Art"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Home & Living"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Fashion & Accessories"
                        });
                });

            modelBuilder.Entity("project_18.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("project_18.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Condition = "Very Good",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A classic 35mm film camera from the 1980s. Excellent aesthetic condition and fully functional shutter.",
                            ImageUrl = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500",
                            IsSold = false,
                            Name = "Retro Film Camera",
                            Price = 320.00m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 4,
                            Condition = "Excellent",
                            CreatedAt = new DateTime(2026, 6, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vintage hand-wound mechanical pocket watch with elegant engravement. Keeps time perfectly.",
                            ImageUrl = "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=500",
                            IsSold = false,
                            Name = "Mechanical Pocket Watch",
                            Price = 180.00m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Condition = "Good",
                            CreatedAt = new DateTime(2026, 6, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentic manual typewriter from the 1970s. All keys strike smoothly. Perfect for writers and collectors.",
                            ImageUrl = "https://images.unsplash.com/photo-1519337265831-281ec6cc8514?w=500",
                            IsSold = false,
                            Name = "Vintage Typewriter",
                            Price = 450.00m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            Condition = "Good",
                            CreatedAt = new DateTime(2026, 6, 4, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genuine brown leather boots, size 42. Nicely broken-in with standard vintage character.",
                            ImageUrl = "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=500",
                            IsSold = false,
                            Name = "Classic Leather Boots",
                            Price = 150.00m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3,
                            Condition = "Very Good",
                            CreatedAt = new DateTime(2026, 6, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handcrafted solid oak rocking chair. Very comfortable, sturdy frame with minor scratches on armrests.",
                            ImageUrl = "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=500",
                            IsSold = false,
                            Name = "Wooden Rocking Chair",
                            Price = 280.00m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Condition = "Excellent",
                            CreatedAt = new DateTime(2026, 6, 6, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-fidelity vintage record player turntable. Built-in stereo speakers and clean retro wood casing.",
                            ImageUrl = "https://images.unsplash.com/photo-1539707132456-a3c44ac79743?w=500",
                            IsSold = false,
                            Name = "Vinyl Record Player",
                            Price = 600.00m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 4,
                            Condition = "Excellent",
                            CreatedAt = new DateTime(2026, 6, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic style sunglasses with a gold metal frame and dark green polarized lenses in great shape.",
                            ImageUrl = "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500",
                            IsSold = false,
                            Name = "Polarized Retro Sunglasses",
                            Price = 90.00m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Condition = "Very Good",
                            CreatedAt = new DateTime(2026, 6, 8, 17, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic six-string acoustic guitar with a warm resonant sound. Includes original gig bag.",
                            ImageUrl = "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=500",
                            IsSold = false,
                            Name = "Acoustic Folk Guitar",
                            Price = 380.00m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            Condition = "Very Good",
                            CreatedAt = new DateTime(2026, 6, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vintage black leather biker jacket, size L. Durable heavy leather with nice distressed edges.",
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
                            IsSold = false,
                            Name = "Classic Leather Jacket",
                            Price = 240.00m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            Condition = "Good",
                            CreatedAt = new DateTime(2026, 6, 10, 19, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mid-century brass table lamp with a green glass banker-style shade. Tested and works perfectly.",
                            ImageUrl = "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500",
                            IsSold = false,
                            Name = "Antique Brass Table Lamp",
                            Price = 190.00m
                        });
                });

            modelBuilder.Entity("project_18.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "BalaMarket Admin",
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("project_18.Models.Order", b =>
                {
                    b.HasOne("project_18.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("project_18.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_18.Models.Product", b =>
                {
                    b.HasOne("project_18.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("project_18.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("project_18.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
